# Site settings
title: nugg.life
email: bongmaster@nugg.life
description: > # this means to ignore newlines until "baseurl:"
 Nuggs for life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nugg.life" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
source: src
destination: build

